import type {
  DashboardMetric,
  WorkTrade,
  ApprovalItem,
  WebTaskAction,
  AgentStatus,
  AuditEventRow,
  IntegrationStatus,
  SafetyPolicyNotice,
} from "./types";

export const MOCK_METRICS: DashboardMetric[] = [
  { label: "전체 작업", value: "12", sub: "건", status: "PASS" },
  { label: "승인 대기", value: "2", sub: "건", status: "WARN" },
  { label: "실행 중", value: "3", sub: "건", status: "PASS" },
  { label: "실패/WARN", value: "1", sub: "건", status: "WARN" },
  { label: "외부 웹 업무", value: "12", sub: "건 분류됨", status: "PASS" },
  { label: "로컬 에이전트", value: "1", sub: "대 온라인", status: "PASS" },
];

export const MOCK_WORK_TRADES: WorkTrade[] = [
  {
    tradeKey: "web-task-engine",
    tradeName: "웹 업무 실행 엔진",
    description: "web-tasks/run, approval gate, audit log",
    classification: "IN_SCOPE",
    executionLocation: "SERVER",
    riskLevel: "medium",
    requiresApproval: true,
    requiresAuth: true,
    status: "PASS",
  },
  {
    tradeKey: "approval-audit",
    tradeName: "승인/감사/task state",
    description: "approval gate, dev_reg_approval, task_state",
    classification: "IN_SCOPE",
    executionLocation: "SERVER",
    riskLevel: "low",
    requiresApproval: false,
    requiresAuth: true,
    status: "PASS",
  },
  {
    tradeKey: "local-agent",
    tradeName: "로컬 에이전트 연결",
    description: "local agent dispatch, execution location guard",
    classification: "IN_SCOPE",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "medium",
    requiresApproval: true,
    requiresAuth: true,
    status: "PASS",
  },
  {
    tradeKey: "admin-web",
    tradeName: "비서앱 웹 페이지",
    description: "admin-web Next.js 운영센터",
    classification: "IN_SCOPE",
    executionLocation: "SERVER",
    riskLevel: "low",
    requiresApproval: false,
    requiresAuth: true,
    status: "PASS",
  },
  {
    tradeKey: "desktop-app",
    tradeName: "비서앱 데스크 앱",
    description: "desktop/tray_app.py, local_runner.py",
    classification: "IN_SCOPE",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "low",
    requiresApproval: false,
    requiresAuth: false,
    status: "WARN",
    notes: "데스크 앱 연결 공정 진행 중",
  },
  {
    tradeKey: "naver-external",
    tradeName: "Naver 외부 웹 업무",
    description: "검색(read-only) + 앱등록/블로그(local agent)",
    classification: "IN_SCOPE",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "medium",
    requiresApproval: true,
    requiresAuth: true,
    status: "PASS",
  },
  {
    tradeKey: "google-external",
    tradeName: "Google 외부 웹 업무",
    description: "OAuth 등록 + Gmail/Cal/Drive API",
    classification: "OFFICIAL_API_OR_OAUTH_REQUIRED",
    executionLocation: "OFFICIAL_API",
    riskLevel: "medium",
    requiresApproval: true,
    requiresAuth: true,
    status: "WARN",
    notes: "OAuth 설정 필요",
  },
  {
    tradeKey: "hwpx-integration",
    tradeName: "HWPX 편집",
    description: "별도 HWP/HWPX 앱 연동 (hancom COM)",
    classification: "EXTERNAL_APP_HOLD",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "low",
    requiresApproval: false,
    requiresAuth: false,
    status: "HOLD",
    notes: "별도 앱 개발 완료 후 연결통로 공사",
  },
  {
    tradeKey: "excel-integration",
    tradeName: "Excel/Office 자동화",
    description: "별도 Excel/Office COM 앱 연동",
    classification: "EXTERNAL_APP_HOLD",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "low",
    requiresApproval: false,
    requiresAuth: false,
    status: "HOLD",
    notes: "별도 앱 개발 완료 후 연결통로 공사",
  },
];

export const MOCK_APPROVAL_QUEUE: ApprovalItem[] = [
  {
    taskId: "wt-a1b2c3d4e5f6",
    taskName: "하이웍스 개발자 앱 등록",
    provider: "hiworks",
    actionType: "developer_apply",
    riskLevel: "high",
    requestedAt: "2026-05-16T09:12:00+09:00",
    expiresAt: "2026-05-16T09:42:00+09:00",
    status: "pending_approval",
    requestedBy: "admin",
  },
  {
    taskId: "wt-f6e5d4c3b2a1",
    taskName: "네이버 개발자 앱 등록",
    provider: "naver",
    actionType: "app_register",
    riskLevel: "high",
    requestedAt: "2026-05-16T08:44:00+09:00",
    expiresAt: "2026-05-16T09:14:00+09:00",
    status: "pending_approval",
    requestedBy: "owner",
  },
];

export const MOCK_WEB_TASKS: WebTaskAction[] = [
  {
    taskKey: "hiworks/developer_apply",
    provider: "hiworks",
    actionType: "developer_apply",
    description: "하이웍스 개발자 센터 앱 등록 신청",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "high",
    requiresApproval: true,
    dryRunSupported: true,
    classification: "WEB_TASK_REGISTRY",
    status: "ready",
  },
  {
    taskKey: "naver/app_register",
    provider: "naver",
    actionType: "app_register",
    description: "네이버 개발자 센터 앱 등록",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "high",
    requiresApproval: true,
    dryRunSupported: true,
    classification: "WEB_TASK_REGISTRY",
    status: "ready",
  },
  {
    taskKey: "google/oauth_submit",
    provider: "google",
    actionType: "oauth_submit",
    description: "Google Cloud Console OAuth 클라이언트 등록",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "high",
    requiresApproval: true,
    dryRunSupported: true,
    classification: "WEB_TASK_REGISTRY",
    status: "ready",
  },
  {
    taskKey: "naver/blog_write",
    provider: "naver",
    actionType: "blog_write",
    description: "네이버 블로그 글 작성/게시",
    executionLocation: "LOCAL_AGENT",
    riskLevel: "high",
    requiresApproval: true,
    dryRunSupported: false,
    classification: "LOCAL_AGENT_REQUIRED",
    status: "agent_required",
  },
  {
    taskKey: "google/gmail_read",
    provider: "google",
    actionType: "gmail_read",
    description: "Gmail 수신함 조회 (OAuth2 필요)",
    executionLocation: "OFFICIAL_API",
    riskLevel: "medium",
    requiresApproval: false,
    dryRunSupported: false,
    classification: "OFFICIAL_API_OR_OAUTH_REQUIRED",
    status: "oauth_required",
  },
];

export const MOCK_AGENT_STATUSES: AgentStatus[] = [
  {
    agentId: "local-agent-01",
    agentName: "로컬 에이전트 (사용자 PC)",
    status: "online",
    lastHeartbeat: "2026-05-16T09:30:00+09:00",
    canReceiveTasks: true,
    userDirectRequired: false,
    serverExecutable: false,
    blockingPolicy: undefined,
  },
  {
    agentId: "desktop-app-01",
    agentName: "데스크 앱 (tray)",
    status: "idle",
    lastHeartbeat: "2026-05-16T09:28:00+09:00",
    canReceiveTasks: true,
    userDirectRequired: true,
    serverExecutable: false,
    blockingPolicy: "USER_DIRECT_REQUIRED for auth/submit",
  },
];

export const MOCK_AUDIT_EVENTS: AuditEventRow[] = [
  {
    eventId: "evt-001",
    eventType: "WEB_TASK_DRY_RUN_COMPLETED",
    taskId: "wt-a1b2c3",
    status: "ok",
    timestamp: "2026-05-16T09:10:00+09:00",
    actor: "admin",
    summary: "hiworks/developer_apply dry_run 완료",
  },
  {
    eventId: "evt-002",
    eventType: "WEB_TASK_PENDING_APPROVAL_CREATED",
    taskId: "wt-a1b2c3d4e5f6",
    status: "ok",
    timestamp: "2026-05-16T09:12:00+09:00",
    actor: "admin",
    summary: "승인 대기 생성 — Telegram 발송 완료",
  },
  {
    eventId: "evt-003",
    eventType: "NAVER_BLOG_SEARCH_READ",
    taskId: "-",
    status: "ok",
    timestamp: "2026-05-16T08:55:00+09:00",
    actor: "owner",
    summary: "네이버 블로그 검색 조회 (total=47)",
  },
  {
    eventId: "evt-004",
    eventType: "WEB_TASK_VALIDATION_FAILED",
    taskId: "wt-fail01",
    status: "warn",
    timestamp: "2026-05-16T08:40:00+09:00",
    actor: "admin",
    summary: "params 검증 실패 — app_name 누락",
  },
];

export const MOCK_INTEGRATIONS: IntegrationStatus[] = [
  {
    key: "naver-search",
    name: "Naver 검색 (read-only)",
    classification: "SERVER_READONLY_ALLOWED",
    connected: true,
    authMethod: "none",
    notes: "/api/v1/external/naver/* 3개 endpoint 활성화됨",
  },
  {
    key: "naver-local-agent",
    name: "Naver 로컬 에이전트 업무",
    classification: "LOCAL_AGENT_REQUIRED",
    connected: false,
    authMethod: "browser_session",
    notes: "로컬 에이전트 + 사전 로그인 필요",
    action: "로컬 에이전트 설정",
  },
  {
    key: "google-oauth",
    name: "Google OAuth/API",
    classification: "OFFICIAL_API_OR_OAUTH_REQUIRED",
    connected: false,
    authMethod: "oauth",
    notes: "credentials.json + token.json 설정 필요",
    action: "OAuth 설정 시작",
  },
  {
    key: "telegram",
    name: "Telegram 알림",
    classification: "IN_SCOPE",
    connected: true,
    authMethod: "bot_token",
    notes: "BOT_TOKEN 설정됨. 승인 알림 발송 활성화",
  },
  {
    key: "hwpx-app",
    name: "HWPX 앱 연동",
    classification: "EXTERNAL_APP_HOLD",
    connected: false,
    authMethod: "none",
    notes: "별도 앱 개발 완료 후 연결통로 공사 예정",
  },
  {
    key: "excel-app",
    name: "Excel/Office 앱 연동",
    classification: "EXTERNAL_APP_HOLD",
    connected: false,
    authMethod: "none",
    notes: "별도 앱 개발 완료 후 연결통로 공사 예정",
  },
];

export const SAFETY_POLICIES: SafetyPolicyNotice[] = [
  {
    id: "sp-01",
    title: "서버 브라우저 계정 로그인 금지",
    description:
      "서버에서 Naver/Google/금융/정부 사이트 계정 로그인 자동화를 실행하지 않습니다.",
    level: "block",
  },
  {
    id: "sp-02",
    title: "실제 제출/투찰/전자서명/결제 사용자 승인 필수",
    description:
      "제출·결제·투찰·전자서명 작업은 사용자 직접 확인 후에만 실행됩니다.",
    level: "block",
  },
  {
    id: "sp-03",
    title: "secret/token/password 응답 노출 금지",
    description:
      "모든 API 응답에서 인증 정보는 제외됩니다. 안전 필드만 노출합니다.",
    level: "block",
  },
  {
    id: "sp-04",
    title: "승인 만료 후 작업 자동 폐기",
    description: "승인 토큰은 30분 TTL. 만료 후 실행 시도는 자동 거부됩니다.",
    level: "warn",
  },
];
