"""네이버 개인 서비스 카탈로그 (auto-generated).

생성: 2026-05-12T08:49:38
원본: data/sitemap/naver_personal_summary.json
로그인 사용자: 조명

사용:
  from scripts.naver.services_catalog import SERVICES, get_service, open_service
  open_service(page, "blog_admin")
  for s in list_services(category="콘텐츠"): ...
"""
from __future__ import annotations

from typing import Any


SERVICES: dict[str, dict[str, Any]] = {
    'naver_main': {
        'url': 'https://www.naver.com/',
        'final_url': 'https://www.naver.com/',
        'category': '포털',
        'desc': '네이버 메인',
        'ok': True,
        'menu_count': 12,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '프로필 설정\n해한 조명님네이버ID\n로그인 보호 설정\ns',
        'menus': [
            {"text": '메일', "href": 'https://mail.naver.com/'},
            {"text": '카페', "href": 'https://cafe.naver.com/'},
            {"text": '블로그', "href": 'https://blog.naver.com/'},
            {"text": '스토어', "href": 'https://shopping.naver.com/ns/home'},
            {"text": '뉴스', "href": 'https://news.naver.com/'},
            {"text": '증권', "href": 'https://finance.naver.com/'},
            {"text": '부동산', "href": 'https://land.naver.com/'},
            {"text": '지도', "href": 'https://map.naver.com/'},
            {"text": '웹툰', "href": 'https://comic.naver.com/'},
            {"text": '치지직', "href": 'https://chzzk.naver.com/?tracking_code=home_recommend'},
            {"text": '바로가기 펼침', "href": 'https://www.naver.com/#'},
            {"text": '쿠쿠 AD', "href": 'https://siape.veta.naver.com/fxclick?eu=EU10044129&calp=-&oj=ZJlEFeSBKmI6O8fOJ%2FRYJzyXzNibtXmbHyIBzTlNu6CX04ZSUNqv3%2BBmGCInJ1A79bVgSpXC5uYBAwIy6E8Q3'},
        ],
    },
    'my_naver': {
        'url': 'https://naver.com/main',
        'final_url': 'https://www.naver.com/',
        'category': '포털',
        'desc': 'My네이버',
        'ok': True,
        'menu_count': 12,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '프로필 설정\n해한 조명님네이버ID\n로그인 보호 설정\ns',
        'menus': [
            {"text": '메일', "href": 'https://mail.naver.com/'},
            {"text": '카페', "href": 'https://cafe.naver.com/'},
            {"text": '블로그', "href": 'https://blog.naver.com/'},
            {"text": '스토어', "href": 'https://shopping.naver.com/ns/home'},
            {"text": '뉴스', "href": 'https://news.naver.com/'},
            {"text": '증권', "href": 'https://finance.naver.com/'},
            {"text": '부동산', "href": 'https://land.naver.com/'},
            {"text": '지도', "href": 'https://map.naver.com/'},
            {"text": '웹툰', "href": 'https://comic.naver.com/'},
            {"text": '치지직', "href": 'https://chzzk.naver.com/?tracking_code=home_recommend'},
            {"text": '바로가기 펼침', "href": 'https://www.naver.com/#'},
            {"text": '센스맘 AD', "href": 'https://siape.veta.naver.com/fxclick?eu=EU10044129&calp=-&oj=ZJlEFeSBKmI6O8fOJ%2FRYJzyXzNibtXmbHyIBzTlNu6CX04ZSUNqv3%2BBmGCInJ1A79bVgSpXC5uYBAwIy6E8Q3'},
        ],
    },
    'nid_profile': {
        'url': 'https://nid.naver.com/user2/help/myInfoV2',
        'final_url': 'https://nid.naver.com/user2/help/myInfoV2',
        'category': '계정',
        'desc': '내 정보',
        'ok': True,
        'menu_count': 11,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": '네이버', "href": 'https://www.naver.com/'},
            {"text": '네이버ID', "href": 'https://nid.naver.com/user2/help/myInfoV2?lang=ko_KR'},
            {"text": '프로필 수정하기', "href": 'https://nid.naver.com/user2/help/myInfoV2#'},
            {"text": '내프로필', "href": 'https://nid.naver.com/user2/help/myInfoV2?m=viewProfile&lang=ko_KR'},
            {"text": '보안설정', "href": 'https://nid.naver.com/user2/help/myInfoV2?m=viewSecurity&lang=ko_KR'},
            {"text": '이력관리', "href": 'https://nid.naver.com/user2/help/myInfoV2?m=viewManageHistory&lang=ko_KR'},
            {"text": '스마트봇 상담', "href": 'https://nca.naver.com/chat/account/view'},
            {"text": '회원톡톡', "href": 'https://talk.naver.com/ct/wc4bsu#nafullscreen'},
            {"text": '로그아웃', "href": 'javascript:;'},
            {"text": '고객센터', "href": 'javascript:;'},
            {"text": '한국어', "href": 'javascript:;'},
        ],
    },
    'nid_security': {
        'url': 'https://nid.naver.com/user2/help/secureV2',
        'final_url': 'https://nid.naver.com/user2/help/secureV2',
        'category': '계정',
        'desc': '보안 설정',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
        ],
    },
    'blog_admin': {
        'url': 'https://admin.blog.naver.com/',
        'final_url': 'https://admin.blog.naver.com/',
        'category': '콘텐츠',
        'desc': '블로그 관리',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
        ],
    },
    'blog_my': {
        'url': 'https://blog.naver.com/skyjwsin',
        'final_url': 'https://blog.naver.com/skyjwsin',
        'category': '콘텐츠',
        'desc': '내 블로그',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
        ],
    },
    'blog_stats': {
        'url': 'https://blog.naver.com/PostWriteFormDocControl.naver?blogId=skyjwsin',
        'final_url': 'https://blog.naver.com/PostWriteFormDocControl.naver?blogId=skyjwsin',
        'category': '콘텐츠',
        'desc': '블로그 통계',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
        ],
    },
    'influencer': {
        'url': 'https://in.naver.com/',
        'final_url': 'https://in.naver.com/discover',
        'category': '콘텐츠',
        'desc': '인플루언서 센터',
        'ok': True,
        'menu_count': 8,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '단골고객',
        'menus': [
            {"text": '네이버', "href": 'https://www.naver.com/'},
            {"text": '인플루언서', "href": 'https://in.naver.com/discover'},
            {"text": '로그아웃', "href": 'https://nid.naver.com/nidlogin.logout?returl=https://in.naver.com/discover'},
            {"text": '공식블로그', "href": 'https://blog.naver.com/influencer_search'},
            {"text": '네이버 인플루언서 센터', "href": 'https://influencercenter.naver.com/'},
            {"text": '운영정책', "href": 'https://in.naver.com/servicePolicy?anchor=footer'},
            {"text": '고객센터', "href": 'https://help.naver.com/alias/search/influencer/main.naver'},
            {"text": '개인정보 처리방침', "href": 'https://policy.naver.com/rules/privacy.html'},
        ],
    },
    'series': {
        'url': 'https://series.naver.com/',
        'final_url': 'https://series.naver.com/novel/home.series?isWebtoonAgreePopUp=true',
        'category': '콘텐츠',
        'desc': '시리즈',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '대표',
        'menus': [
        ],
    },
    'moment': {
        'url': 'https://m.blog.naver.com/MomentFeed.naver',
        'final_url': 'https://m.blog.naver.com/MobileErrorView.naver?errorType=notfound&isBackAllowForInApp=null',
        'category': '콘텐츠',
        'desc': '모먼트',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
        ],
    },
    'cafe_my': {
        'url': 'https://section.cafe.naver.com/ca-fe/home/recent-articles',
        'final_url': 'https://section.cafe.naver.com/ca-fe/home/recent-articles',
        'category': '커뮤니티',
        'desc': '내 카페',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
        ],
    },
    'cafe_admin': {
        'url': 'https://cafe.naver.com/ManageCafe.nhn',
        'final_url': 'https://cafe.naver.com/ManageCafe.nhn',
        'category': '커뮤니티',
        'desc': '카페 관리',
        'ok': True,
        'menu_count': 2,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": '네이버홈', "href": 'https://www.naver.com/'},
            {"text": '네이버 고객센터', "href": 'http://help.naver.com/'},
        ],
    },
    'talk': {
        'url': 'https://talk.naver.com/',
        'final_url': 'https://talk.naver.com/',
        'category': '커뮤니티',
        'desc': '톡톡',
        'ok': True,
        'menu_count': 4,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": '네이버', "href": 'http://www.naver.com/'},
            {"text": '톡톡', "href": 'https://talk.naver.com/'},
            {"text": '해한 조명 내정보 보기', "href": 'javascript:;'},
            {"text": '서비스 더보기', "href": 'javascript:;'},
        ],
    },
    'band': {
        'url': 'https://band.us/',
        'final_url': 'https://www.band.us/about/kr/intro',
        'category': '커뮤니티',
        'desc': '밴드',
        'ok': True,
        'menu_count': 3,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": 'BAND', "href": 'https://www.band.us/'},
            {"text": '회원가입', "href": 'https://auth.band.us/sign_up_form?next_url=https%3A%2F%2Fwww.band.us'},
            {"text": '로그인', "href": 'https://auth.band.us/login_page?next_url=https%3A%2F%2Fwww.band.us'},
        ],
    },
    'mail': {
        'url': 'https://mail.naver.com/',
        'final_url': 'https://mail.naver.com/v2/folders/0/all',
        'category': '메일',
        'desc': '네이버 메일',
        'ok': True,
        'menu_count': 40,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '재우',
        'menus': [
            {"text": 'NAVER', "href": 'https://www.naver.com/'},
            {"text": '메일', "href": 'https://mail.naver.com/'},
            {"text": '해한 조명 내정보 보기', "href": 'javascript:;'},
            {"text": '네이버톡', "href": 'https://talks.naver.com/?frm=pcgnb&anchor=&category='},
            {"text": '알림', "href": 'https://m.notify.naver.com/?from=pcmain'},
            {"text": '서비스 더보기', "href": 'javascript:;'},
            {"text": '캘린더', "href": 'https://calendar.naver.com/'},
            {"text": '메모', "href": 'https://memo.naver.com/'},
            {"text": '주소록', "href": 'https://contact.naver.com/'},
            {"text": 'MYBOX', "href": 'https://mybox.naver.com/'},
            {"text": '가계부', "href": 'https://moneybook.naver.com/'},
            {"text": 'Keep', "href": 'https://keep.naver.com/'},
            {"text": '메일 쓰기', "href": 'https://mail.naver.com/v2/folders/0/all#'},
            {"text": '내게 쓰기', "href": 'https://mail.naver.com/v2/folders/0/all#'},
            {"text": '207 개의 안읽음 메일 목록 선택됨', "href": 'https://mail.naver.com/v2/folders/0/all#'},
            {"text": '중요 표시된 메일 목록', "href": 'https://mail.naver.com/v2/folders/0/all#'},
            {"text": '첨부 파일이 포함된 메일 목록', "href": 'https://mail.naver.com/v2/folders/0/all#'},
            {"text": 'TO 받은 사람이 나인 메일 목록', "href": 'https://mail.naver.com/v2/folders/0/all#'},
            {"text": '전체메일', "href": 'https://mail.naver.com/v2/folders/0/all#'},
            {"text": '받은메일함 선택됨', "href": 'https://mail.naver.com/v2/folders/0/all#'},
        ],
    },
    'calendar': {
        'url': 'https://calendar.naver.com/',
        'final_url': 'https://calendar.naver.com/main#%7B%22sSection%22%3A%22scheduleMain%22%2C%22oParameter%22%3A%7B%22sViewType%22%3A%22month%22%2C%22sDate%22%3A%222026-05-12%22%7D%7D',
        'category': '일정',
        'desc': '네이버 캘린더',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '부처',
        'menus': [
        ],
    },
    'mybox': {
        'url': 'https://mybox.naver.com/',
        'final_url': 'https://mybox.naver.com/main/web/my',
        'category': '클라우드',
        'desc': '마이박스',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '측정표-사장',
        'menus': [
        ],
    },
    'pay': {
        'url': 'https://pay.naver.com/',
        'final_url': 'https://pay.naver.com/pc/history?page=1',
        'category': '결제',
        'desc': '네이버 페이',
        'ok': True,
        'menu_count': 3,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": '네이버', "href": 'https://naver.com/'},
            {"text": '네이버페이', "href": 'https://pay.naver.com/pc/history'},
            {"text": '결제', "href": 'https://pay.naver.com/pc/history'},
        ],
    },
    'pay_history': {
        'url': 'https://order.pay.naver.com/home',
        'final_url': 'https://pay.naver.com/pc/history?page=1',
        'category': '결제',
        'desc': '결제 내역',
        'ok': True,
        'menu_count': 3,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": '네이버', "href": 'https://naver.com/'},
            {"text": '네이버페이', "href": 'https://pay.naver.com/pc/history'},
            {"text": '결제', "href": 'https://pay.naver.com/pc/history'},
        ],
    },
    'mybiz': {
        'url': 'https://mybiz.pay.naver.com/dashboard',
        'final_url': 'https://mybiz.pay.naver.com/dashboard',
        'category': '결제',
        'desc': '마이비즈',
        'ok': True,
        'menu_count': 2,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '신재우',
        'menus': [
            {"text": '내 사업 현황', "href": 'https://mybiz.pay.naver.com/dashboard#status'},
            {"text": '내 사업 지원', "href": 'https://mybiz.pay.naver.com/dashboard#support'},
        ],
    },
    'pay_point': {
        'url': 'https://nid.naver.com/user2/help/payV2',
        'final_url': 'https://nid.naver.com/user2/help/payV2',
        'category': '결제',
        'desc': '포인트 관리',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
        ],
    },
    'smartstore': {
        'url': 'https://sell.smartstore.naver.com/#/home/dashboard',
        'final_url': 'https://sell.smartstore.naver.com/#/home/dashboard',
        'category': '커머스',
        'desc': '스마트스토어 셀러센터',
        'ok': True,
        'menu_count': 9,
        'has_logout': True,
        'access_denied': False,
        'user_shown': 'skyjwsin',
        'menus': [
            {"text": '네이버', "href": ''},
            {"text": '스마트스토어센터', "href": 'https://sell.smartstore.naver.com/#/home/dashboard'},
            {"text": '쇼핑파트너센터', "href": 'https://center.shopping.naver.com/'},
            {"text": '커머스솔루션마켓', "href": 'https://solution.smartstore.naver.com/'},
            {"text": '광고주센터', "href": 'https://ads.naver.com/'},
            {"text": '마이비즈', "href": 'https://mybiz.pay.naver.com/dashboard'},
            {"text": 'skyjwsin님내정보', "href": 'https://sell.smartstore.naver.com/#/seller/member'},
            {"text": '스토어 이동', "href": 'https://sell.smartstore.naver.com/'},
            {"text": '로그아웃', "href": 'https://sell.smartstore.naver.com/'},
        ],
    },
    'shopping_partner': {
        'url': 'https://center.shopping.naver.com/',
        'final_url': 'https://center.shopping.naver.com/main',
        'category': '커머스',
        'desc': '쇼핑파트너센터',
        'ok': True,
        'menu_count': 12,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": '로그아웃', "href": 'https://center.shopping.naver.com/v1/logout'},
            {"text": '광고상품안내', "href": 'https://join.shopping.naver.com/ad/theme/shopping_box.nhn'},
            {"text": '도움말', "href": 'https://join.shopping.naver.com/faq/list.nhn?catgCd=F10001'},
            {"text": '온라인상담', "href": "javascript:window.open('https://talk.naver.com/ct/wc3n30', '', 'width=500,height=150');"},
            {"text": '정보관리', "href": 'https://center.shopping.naver.com/seller/info'},
            {"text": '충전/계좌관리', "href": 'https://center.shopping.naver.com/account/charge'},
            {"text": '상품관리', "href": 'https://center.shopping.naver.com/product/receive'},
            {"text": '상품리포트', "href": 'https://center.shopping.naver.com/report/order'},
            {"text": 'PC광고관리 NEW', "href": 'https://center.shopping.naver.com/shopping-advertisement/pc-sa-information'},
            {"text": '모바일광고관리', "href": 'https://center.shopping.naver.com/advertisement/mobile'},
            {"text": '광고리포트/공통관리', "href": 'https://center.shopping.naver.com/report/ad/dashboard'},
            {"text": '문의/공지', "href": 'https://center.shopping.naver.com/comments/notice'},
        ],
    },
    'commerce_solution': {
        'url': 'https://solution.smartstore.naver.com/',
        'final_url': 'https://solution.smartstore.naver.com/ko/home',
        'category': '커머스',
        'desc': '커머스솔루션마켓',
        'ok': True,
        'menu_count': 4,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '반딧불 아뜰리에',
        'menus': [
            {"text": 'NAVER', "href": 'https://www.naver.com/'},
            {"text": '커머스솔루션마켓', "href": 'https://solution.smartstore.naver.com/ko'},
            {"text": '스마트스토어센터', "href": 'https://sell.smartstore.naver.com/#/home'},
            {"text": '반딧불 아뜰리에', "href": 'javascript:void(0);'},
        ],
    },
    'ads': {
        'url': 'https://ads.naver.com/',
        'final_url': 'https://ads.naver.com/signup/agree',
        'category': '광고',
        'desc': '광고주센터',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': True,
        'user_shown': '광고주',
        'menus': [
        ],
    },
    'ad_searchad': {
        'url': 'https://searchad.naver.com/',
        'final_url': 'https://ads.naver.com/signup/agree',
        'category': '광고',
        'desc': '검색광고',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': True,
        'user_shown': '광고주',
        'menus': [
        ],
    },
    'ad_smartchannel': {
        'url': 'https://saedu.naver.com/',
        'final_url': 'https://ads.naver.com/signup/agree',
        'category': '광고',
        'desc': '성과형 광고',
        'ok': True,
        'menu_count': 0,
        'has_logout': False,
        'access_denied': True,
        'user_shown': '광고주',
        'menus': [
        ],
    },
    'maps_my': {
        'url': 'https://map.naver.com/p/?c=My',
        'final_url': 'https://map.naver.com/p/?c=My',
        'category': '도구',
        'desc': '내 지도',
        'ok': True,
        'menu_count': 3,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": '네이버지도', "href": 'https://www.naver.com/'},
            {"text": '내정보 보기', "href": 'javascript:;'},
            {"text": '서비스 더보기', "href": 'javascript:;'},
        ],
    },
    'place_owner': {
        'url': 'https://new.smartplace.naver.com/',
        'final_url': 'https://new.smartplace.naver.com/',
        'category': '도구',
        'desc': '스마트플레이스',
        'ok': True,
        'menu_count': 11,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '조명',
        'menus': [
            {"text": '네이버', "href": 'https://www.naver.com/'},
            {"text": '스마트플레이스', "href": 'https://new.smartplace.naver.com/'},
            {"text": '광고주센터', "href": 'https://ads.naver.com/'},
            {"text": '톡톡', "href": 'https://partner.talk.naver.com/'},
            {"text": '스마트스토어', "href": 'https://sell.smartstore.naver.com/'},
            {"text": '페이', "href": 'https://admin.pay.naver.com/'},
            {"text": '교육', "href": 'https://m.site.naver.com/1oMN7'},
            {"text": '마이비즈', "href": 'https://mybiz.pay.naver.com/dashboard'},
            {"text": '해한 조명님', "href": 'https://new.smartplace.naver.com/my'},
            {"text": '로그아웃', "href": ''},
            {"text": '메뉴보기', "href": 'https://new.smartplace.naver.com/#'},
        ],
    },
    'clova': {
        'url': 'https://clova.ai/ko',
        'final_url': 'https://clova.ai/',
        'category': 'AI',
        'desc': 'Clova',
        'ok': True,
        'menu_count': 15,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": 'HyperCLOVA X', "href": 'https://clova.ai/hyperclova'},
            {"text": 'Tech Blog', "href": 'https://clova.ai/tech-blog'},
            {"text": 'AI Research', "href": 'https://clova.ai/ai-research'},
            {"text": '파트너 제휴', "href": 'https://www.ncloud.com/partner/program/'},
            {"text": '문의하기', "href": 'https://www.ncloud.com/support/question/sales?parentCode=SALES_PNSTS'},
            {"text": '# 하이퍼클로바X', "href": 'https://clova.ai/tech-blog/tag/%ED%95%98%EC%9D%B4%ED%8D%BC%ED%81%B4%EB%A1%9C%EB%B0%94x'},
            {"text": '# 네이버AI', "href": 'https://clova.ai/tech-blog/tag/%EB%84%A4%EC%9D%B4%EB%B2%84ai'},
            {"text": '# 클로바스튜디오', "href": 'https://clova.ai/tech-blog/tag/%ED%81%B4%EB%A1%9C%EB%B0%94%EC%8A%A4%ED%8A%9C%EB%94%94%EC%98%A4'},
            {"text": '# 소버린AI', "href": 'https://clova.ai/tech-blog/tag/%EC%86%8C%EB%B2%84%EB%A6%B0ai'},
            {"text": '# HCI', "href": 'https://clova.ai/tech-blog/tag/hci'},
            {"text": '# AI Research', "href": 'https://clova.ai/tech-blog/tag/ai-research'},
            {"text": '# Audio LLM', "href": 'https://clova.ai/tech-blog/tag/audio-llm'},
            {"text": '# AI Safety', "href": 'https://clova.ai/tech-blog/tag/ai-safety'},
            {"text": '# 포용적 AI', "href": 'https://clova.ai/tech-blog/tag/%ED%8F%AC%EC%9A%A9%EC%A0%81-ai'},
            {"text": '# 오픈소스', "href": 'https://clova.ai/tech-blog/tag/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4'},
        ],
    },
    'webtoon': {
        'url': 'https://comic.naver.com/index',
        'final_url': 'https://comic.naver.com/index',
        'category': '엔터',
        'desc': '네이버 웹툰',
        'ok': True,
        'menu_count': 13,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '시녀',
        'menus': [
            {"text": 'NAVER', "href": 'https://naver.com/'},
            {"text": '웹툰', "href": 'https://comic.naver.com/index'},
            {"text": '웹소설', "href": 'https://novel.naver.com/'},
            {"text": '시리즈', "href": 'https://series.naver.com/'},
            {"text": '해한 조명 내정보 보기', "href": 'javascript:;'},
            {"text": '네이버톡', "href": 'https://talks.naver.com/?frm=pcgnb&anchor=&category='},
            {"text": '알림', "href": 'https://m.notify.naver.com/?from=pcmain'},
            {"text": '메일 99+', "href": 'https://mail.naver.com/'},
            {"text": '서비스 더보기', "href": 'javascript:;'},
            {"text": '컷츠', "href": 'https://comic.naver.com/cuts/v'},
            {"text": '베스트도전', "href": 'https://comic.naver.com/bestChallenge'},
            {"text": '도전만화', "href": 'https://comic.naver.com/challenge'},
            {"text": '마이페이지', "href": 'https://comic.naver.com/mypage/favorite'},
        ],
    },
    'vibe': {
        'url': 'https://vibe.naver.com/',
        'final_url': 'https://vibe.naver.com/today',
        'category': '엔터',
        'desc': 'VIBE 음악',
        'ok': True,
        'menu_count': 12,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": 'VIBE', "href": 'https://vibe.naver.com/'},
            {"text": '>전체 메뉴 닫기', "href": 'https://vibe.naver.com/today#'},
            {"text": '해한 조명 구독중인 멤버십이 없습니다.', "href": 'javascript: void(0)'},
            {"text": '멤버십 구독', "href": 'https://vibe.naver.com/membership/vibe?nopopup=true&nocapsule=true'},
            {"text": '투데이 현재 페이지', "href": 'https://vibe.naver.com/today#'},
            {"text": '차트', "href": 'https://vibe.naver.com/today#'},
            {"text": '오디오', "href": 'https://vibe.naver.com/today#'},
            {"text": '보관함', "href": 'https://vibe.naver.com/today#'},
            {"text": '서비스소개', "href": 'https://vibe.naver.com/today#'},
            {"text": '내돈내듣', "href": 'https://vibe.naver.com/today#'},
            {"text": '이용권선물', "href": 'https://vibe.naver.com/today#'},
            {"text": '데스크톱앱 설치', "href": 'https://vibe.naver.com/desktopapp'},
        ],
    },
    'tv': {
        'url': 'https://tv.naver.com/',
        'final_url': 'https://tv.naver.com/',
        'category': '엔터',
        'desc': '네이버 TV',
        'ok': True,
        'menu_count': 23,
        'has_logout': False,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": 'NAVER TV', "href": 'https://tv.naver.com/'},
            {"text": '생중계', "href": 'https://tv.naver.com/l'},
            {"text": '클립', "href": 'https://tv.naver.com/h'},
            {"text": '구독', "href": 'https://tv.naver.com/f'},
            {"text": '최근 본 영상', "href": 'https://tv.naver.com/my?tab=recent'},
            {"text": '좋아요 한 영상', "href": 'https://tv.naver.com/my?tab=liked'},
            {"text": '나중에 볼 영상', "href": 'https://tv.naver.com/my?tab=saved'},
            {"text": 'TOP100', "href": 'https://tv.naver.com/r'},
            {"text": '급상승', "href": 'https://tv.naver.com/i'},
            {"text": '뉴스', "href": 'https://tv.naver.com/ct/news'},
            {"text": '스포츠', "href": 'https://tv.naver.com/ct/sport'},
            {"text": '드라마', "href": 'https://tv.naver.com/ct/drama'},
            {"text": '예능', "href": 'https://tv.naver.com/ct/enter'},
            {"text": '더 많은 영상', "href": 'https://tv.naver.com/ct/other'},
            {"text": 'TV 조선', "href": 'https://tv.naver.com/b/tvchosun'},
            {"text": 'MBN', "href": 'https://tv.naver.com/b/mbn'},
            {"text": 'CHANNEL A', "href": 'https://tv.naver.com/b/channela'},
            {"text": 'JTBC', "href": 'https://tv.naver.com/b/jtbc'},
            {"text": 'KBS', "href": 'https://tv.naver.com/b/kbs'},
            {"text": 'MBC', "href": 'https://tv.naver.com/b/mbc'},
        ],
    },
    'sports': {
        'url': 'https://sports.news.naver.com/',
        'final_url': 'https://m.sports.naver.com/index',
        'category': '엔터',
        'desc': '스포츠',
        'ok': True,
        'menu_count': 24,
        'has_logout': True,
        'access_denied': False,
        'user_shown': '',
        'menus': [
            {"text": 'NAVER', "href": 'https://www.naver.com/'},
            {"text": '스포츠', "href": 'https://sports.news.naver.com/index'},
            {"text": '뉴스', "href": 'https://news.naver.com/'},
            {"text": '엔터', "href": 'https://entertain.naver.com/home'},
            {"text": '해한 조명 내정보 보기', "href": 'javascript:;'},
            {"text": '네이버톡', "href": 'https://talks.naver.com/sports?frm=pcgnb'},
            {"text": '알림', "href": 'https://m.notify.naver.com/?from=pcmain'},
            {"text": '메일 99+', "href": 'https://mail.naver.com/'},
            {"text": '야구', "href": 'https://m.sports.naver.com/kbaseball/index'},
            {"text": '해외야구', "href": 'https://m.sports.naver.com/wbaseball/index'},
            {"text": '축구', "href": 'https://m.sports.naver.com/kfootball/index'},
            {"text": '해외축구', "href": 'https://m.sports.naver.com/wfootball/index'},
            {"text": '농구', "href": 'https://m.sports.naver.com/basketball/index'},
            {"text": '배구', "href": 'https://m.sports.naver.com/volleyball/index'},
            {"text": 'N골프', "href": 'https://m.sports.naver.com/golf/index'},
            {"text": '일반', "href": 'https://m.sports.naver.com/general/index'},
            {"text": 'e스포츠', "href": 'https://game.naver.com/esports'},
            {"text": '아웃도어 NEW', "href": 'https://m.sports.naver.com/outdoor/index'},
            {"text": 'MY팀 설정', "href": 'https://m.sports.naver.com/myteam/index'},
            {"text": '오늘의 경기', "href": 'https://m.sports.naver.com/scoreboard/index'},
        ],
    },
}


def get_service(name: str) -> dict | None:
    """서비스 메타데이터 조회."""
    return SERVICES.get(name)


def list_services(category: str | None = None,
                  only_accessible: bool = False) -> list[dict]:
    """서비스 목록 조회.

    Args:
        category: 카테고리 필터 (포털/콘텐츠/커뮤니티/메일/일정/...)
        only_accessible: True면 access_denied=False만 반환
    """
    items = []
    for name, meta in SERVICES.items():
        if category and meta.get("category") != category:
            continue
        if only_accessible and meta.get("access_denied"):
            continue
        items.append({"name": name, **meta})
    return items


def open_service(page, name: str, timeout_ms: int = 15000) -> bool:
    """서비스 페이지로 이동."""
    svc = SERVICES.get(name)
    if not svc:
        return False
    try:
        page.goto(svc["url"], timeout=timeout_ms, wait_until="domcontentloaded")
        return True
    except Exception:
        return False


def categories() -> list[str]:
    """전체 카테고리 목록."""
    return sorted({s["category"] for s in SERVICES.values()})


CATEGORIES = sorted({s["category"] for s in SERVICES.values()})
TOTAL_SERVICES = 34
ACCESSIBLE_SERVICES = 31
GENERATED_AT = '2026-05-12T08:49:38'
