"""scripts.site_engine — 범용 사이트 자동화 엔진 기반."""

from scripts.site_engine.action_planner import (
    ActionPlan,
    ActionPlanResult,
    ActionPlanRisk,
    ActionPlanStatus,
    ActionPlanStep,
    append_gate_decision,
    build_action_plan,
    require_gate_for_sensitive_action,
    summarize_action_plan,
)
from scripts.site_engine.adapters.browser import (
    BrowserActionKind,
    BrowserActionPlan,
    BrowserActionResult,
    build_click_plan,
    build_download_plan,
    build_input_plan,
    build_readonly_navigation_plan,
    build_submit_plan,
    build_upload_plan,
)
from scripts.site_engine.audit import (
    SiteEngineAuditEvent,
    build_audit_event,
    mask_sensitive,
)
from scripts.site_engine.capability_detector import (
    CapabilityDetectionInput,
    CapabilityDetectionResult,
    PageCapability,
    detect_capabilities_from_snapshot,
)
from scripts.site_engine.execution_gate import (
    ActionSensitivity,
    ExecutionDecision,
    ExecutionGateInput,
    ExecutionGateResult,
    GateReason,
    block_for_sensitive_credential_action,
    evaluate_execution_gate,
    require_approval_for_action,
    resolve_execution_location,
)
from scripts.site_engine.form_resolver import (
    FormFieldCandidate,
    FormFieldKind,
    FormFieldSensitivity,
    FormResolutionInput,
    FormResolutionResult,
    classify_field_sensitivity,
    mask_field_value,
    resolve_form_fields,
)
from scripts.site_engine.profiles import SiteActionPolicy, SiteProfile
from scripts.site_engine.registry import SiteProfileRegistry, get_default_registry
from scripts.site_engine.site_types import (
    ExecutionLocation,
    GateDecision,
    SiteActionKind,
    SiteCapability,
    SiteProfileStatus,
)
from scripts.site_engine.validators import (
    ValidationIssue,
    ValidationResult,
    validate_action_plan_steps,
    validate_no_blocked_step_executable,
    validate_no_executable_sensitive_step_without_gate,
    validate_no_plain_secret,
    validate_workflow_has_profile,
)
from scripts.site_engine.workflow_runner import (
    WorkflowDefinition,
    WorkflowRunPlan,
    WorkflowRunResult,
    WorkflowStatus,
    WorkflowStep,
    attach_action_plan,
    attach_gate_result,
    build_workflow_plan,
    validate_workflow_plan,
)

__all__ = [
    "ActionPlan",
    "ActionPlanResult",
    "ActionPlanRisk",
    "ActionPlanStatus",
    "ActionPlanStep",
    "ActionSensitivity",
    "BrowserActionKind",
    "BrowserActionPlan",
    "BrowserActionResult",
    "CapabilityDetectionInput",
    "CapabilityDetectionResult",
    "ExecutionDecision",
    "ExecutionGateInput",
    "ExecutionGateResult",
    "ExecutionLocation",
    "FormFieldCandidate",
    "FormFieldKind",
    "FormFieldSensitivity",
    "FormResolutionInput",
    "FormResolutionResult",
    "GateDecision",
    "GateReason",
    "PageCapability",
    "SiteActionKind",
    "SiteActionPolicy",
    "SiteCapability",
    "SiteEngineAuditEvent",
    "SiteProfile",
    "SiteProfileRegistry",
    "SiteProfileStatus",
    "ValidationIssue",
    "ValidationResult",
    "WorkflowDefinition",
    "WorkflowRunPlan",
    "WorkflowRunResult",
    "WorkflowStatus",
    "WorkflowStep",
    "append_gate_decision",
    "attach_action_plan",
    "attach_gate_result",
    "block_for_sensitive_credential_action",
    "build_action_plan",
    "build_audit_event",
    "build_click_plan",
    "build_download_plan",
    "build_input_plan",
    "build_readonly_navigation_plan",
    "build_submit_plan",
    "build_upload_plan",
    "build_workflow_plan",
    "classify_field_sensitivity",
    "detect_capabilities_from_snapshot",
    "evaluate_execution_gate",
    "get_default_registry",
    "mask_field_value",
    "mask_sensitive",
    "require_approval_for_action",
    "require_gate_for_sensitive_action",
    "resolve_execution_location",
    "resolve_form_fields",
    "summarize_action_plan",
    "validate_action_plan_steps",
    "validate_no_blocked_step_executable",
    "validate_no_executable_sensitive_step_without_gate",
    "validate_no_plain_secret",
    "validate_workflow_has_profile",
    "validate_workflow_plan",
]
