"""Google service surface catalog.

This module is intentionally static-first. Google login and many Google
workspaces should prefer official OAuth/API paths; browser exploration is
read-only unless explicitly approved by a higher-level workflow.
"""
from __future__ import annotations

from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from scripts.google.common.report_io import save_json_with_latest

ROOT = Path(__file__).resolve().parents[3]
LATEST_CATALOG = ROOT / "data" / "google_surface_catalog_latest.json"
REPORT_DIR = ROOT / "data" / "google_surface_catalogs"


@dataclass(frozen=True)
class GoogleSurface:
    key: str
    label: str
    url: str
    category: str
    access_mode: str
    risk: str
    status: str
    completion_criteria: list[str]
    notes: list[str]


GOOGLE_SURFACES: tuple[GoogleSurface, ...] = (
    GoogleSurface(
        key="google_home",
        label="Google Home",
        url="https://www.google.com/",
        category="search",
        access_mode="browser_readonly",
        risk="read",
        status="scanned_home",
        completion_criteria=[
            "search box, buttons, account/app links captured",
            "bot radar stays clean",
        ],
        notes=["Current live scan reached this surface successfully."],
    ),
    GoogleSurface(
        key="google_account",
        label="Google Account",
        url="https://myaccount.google.com/",
        category="identity",
        access_mode="manual_or_oauth_only",
        risk="auth_sensitive",
        status="gated",
        completion_criteria=[
            "login state is detected without credential replay",
            "account mismatch blocks workflow",
        ],
        notes=["Do not automate credentials; user-present login or OAuth only."],
    ),
    GoogleSurface(
        key="gmail",
        label="Gmail",
        url="https://mail.google.com/mail/u/0/",
        category="workspace",
        access_mode="api_preferred",
        risk="private_data",
        status="implemented_api_partial_browser_gated",
        completion_criteria=[
            "list/compose/send paths use approval where required",
            "browser read is not used for bulk data when API is available",
        ],
        notes=["Existing router supports mail list/compose/send."],
    ),
    GoogleSurface(
        key="drive",
        label="Google Drive",
        url="https://drive.google.com/drive/u/0/",
        category="workspace",
        access_mode="api_preferred",
        risk="private_data",
        status="partial",
        completion_criteria=[
            "file list/search actions have API-backed path",
            "write/delete/download require explicit approval",
        ],
        notes=["Prefer Drive API/OAuth over browser automation."],
    ),
    GoogleSurface(
        key="calendar",
        label="Google Calendar",
        url="https://calendar.google.com/calendar/u/0/r",
        category="workspace",
        access_mode="api_preferred",
        risk="private_data_write_possible",
        status="partial",
        completion_criteria=[
            "read-only calendar state can be captured",
            "create/update/delete require approval and dry-run",
        ],
        notes=["Prefer Calendar API/OAuth."],
    ),
    GoogleSurface(
        key="docs",
        label="Google Docs",
        url="https://docs.google.com/document/u/0/",
        category="workspace",
        access_mode="api_preferred",
        risk="private_data_write_possible",
        status="partial",
        completion_criteria=[
            "recent/open actions are separated from edit actions",
            "document edits require approval and evidence",
        ],
        notes=["Prefer Docs API/OAuth for document operations."],
    ),
    GoogleSurface(
        key="sheets",
        label="Google Sheets",
        url="https://docs.google.com/spreadsheets/u/0/",
        category="workspace",
        access_mode="api_preferred",
        risk="private_data_write_possible",
        status="partial",
        completion_criteria=[
            "recent/open actions are separated from cell edits",
            "cell edits require approval and dry-run",
        ],
        notes=["Prefer Sheets API/OAuth for spreadsheet operations."],
    ),
    GoogleSurface(
        key="cloud_console",
        label="Google Cloud Console",
        url="https://console.cloud.google.com/",
        category="developer_console",
        access_mode="manual_live_read_or_api",
        risk="billing_infra_write_possible",
        status="cataloged",
        completion_criteria=[
            "project/account context is recorded before any action",
            "write/billing/IAM/deploy actions are approval gated",
        ],
        notes=["Read-only exploration only unless separately approved."],
    ),
    GoogleSurface(
        key="search_console",
        label="Google Search Console",
        url="https://search.google.com/search-console",
        category="site_console",
        access_mode="manual_live_read_or_api",
        risk="site_property_data",
        status="cataloged",
        completion_criteria=[
            "property selector state is recorded",
            "indexing/submission actions require approval",
        ],
        notes=["Use official APIs where practical."],
    ),
    GoogleSurface(
        key="ai_studio",
        label="Google AI Studio",
        url="https://aistudio.google.com/",
        category="ai_console",
        access_mode="manual_live_read",
        risk="model_key_project_write_possible",
        status="cataloged",
        completion_criteria=[
            "project/API key context is identified read-only",
            "key creation/model calls require approval",
        ],
        notes=["Do not generate keys or submit prompts without approval."],
    ),
    GoogleSurface(
        key="gemini",
        label="Gemini",
        url="https://gemini.google.com/",
        category="ai_app",
        access_mode="manual_live_read",
        risk="private_prompt_data",
        status="cataloged",
        completion_criteria=[
            "account context is verified",
            "prompt submission requires user intent",
        ],
        notes=["Read-only UI mapping first."],
    ),
    GoogleSurface(
        key="android_developers",
        label="Android Developers",
        url="https://developer.android.com/",
        category="android_docs",
        access_mode="browser_readonly",
        risk="public_read",
        status="cataloged",
        completion_criteria=[
            "documentation navigation is mapped",
            "no login-required action is attempted",
        ],
        notes=["Public docs surface."],
    ),
    GoogleSurface(
        key="play_console",
        label="Google Play Console",
        url="https://play.google.com/console/",
        category="android_console",
        access_mode="manual_live_read",
        risk="app_release_billing_write_possible",
        status="cataloged",
        completion_criteria=[
            "developer account/app context is recorded",
            "release, pricing, policy, user changes require approval",
        ],
        notes=["Never submit app/release changes without dry-run and approval."],
    ),
    GoogleSurface(
        key="firebase_console",
        label="Firebase Console",
        url="https://console.firebase.google.com/",
        category="developer_console",
        access_mode="manual_live_read_or_api",
        risk="infra_data_write_possible",
        status="cataloged",
        completion_criteria=[
            "project context is recorded",
            "rules, deploy, key, billing changes require approval",
        ],
        notes=["Prefer official APIs/CLI for controlled changes."],
    ),
    GoogleSurface(
        key="youtube",
        label="YouTube",
        url="https://www.youtube.com/",
        category="media",
        access_mode="browser_readonly",
        risk="account_media_interaction",
        status="cataloged",
        completion_criteria=[
            "home/account state is captured read-only",
            "like/comment/subscribe/upload actions require approval",
        ],
        notes=["Manual login smoke policy already treats login completion carefully."],
    ),
    GoogleSurface(
        key="youtube_studio",
        label="YouTube Studio",
        url="https://studio.youtube.com/",
        category="creator_console",
        access_mode="manual_live_read_or_api",
        risk="channel_publish_monetization_write_possible",
        status="cataloged",
        completion_criteria=[
            "channel context is recorded",
            "upload, publish, edit, analytics export actions are separated",
            "publish/edit actions require approval and dry-run",
        ],
        notes=["Use YouTube Data API where available for controlled workflows."],
    ),
)


GOOGLE_CORE_SURFACES = GOOGLE_SURFACES

GOOGLE_SURFACES = GOOGLE_CORE_SURFACES + (
    GoogleSurface(
        key="slides",
        label="Google Slides",
        url="https://docs.google.com/presentation/u/0/",
        category="workspace",
        access_mode="api_preferred",
        risk="private_data_write_possible",
        status="cataloged",
        completion_criteria=["recent/open actions separated from edits", "presentation edits require approval"],
        notes=["Workspace presentation surface."],
    ),
    GoogleSurface(
        key="forms",
        label="Google Forms",
        url="https://docs.google.com/forms/u/0/",
        category="workspace",
        access_mode="manual_live_read_or_api",
        risk="private_data_write_possible",
        status="cataloged",
        completion_criteria=["form list/create/edit separated", "publish/share/response changes require approval"],
        notes=["Forms creation and response handling are state-changing."],
    ),
    GoogleSurface(
        key="meet",
        label="Google Meet",
        url="https://meet.google.com/",
        category="workspace",
        access_mode="manual_live_read",
        risk="meeting_join_or_create_possible",
        status="cataloged",
        completion_criteria=["meeting list/join/create controls classified", "join/create requires approval"],
        notes=["Do not join or start calls without user approval."],
    ),
    GoogleSurface(
        key="chat",
        label="Google Chat",
        url="https://chat.google.com/",
        category="workspace",
        access_mode="manual_live_read_or_api",
        risk="message_send_possible",
        status="cataloged",
        completion_criteria=["spaces/direct messages classified", "message sending requires approval"],
        notes=["Use APIs where available for controlled messages."],
    ),
    GoogleSurface(
        key="contacts",
        label="Google Contacts",
        url="https://contacts.google.com/",
        category="workspace",
        access_mode="manual_live_read_or_api",
        risk="contact_data_write_possible",
        status="cataloged",
        completion_criteria=["contacts read/create/update/delete separated", "mutations require approval"],
        notes=["Private contact data surface."],
    ),
    GoogleSurface(
        key="keep",
        label="Google Keep",
        url="https://keep.google.com/",
        category="workspace",
        access_mode="manual_live_read",
        risk="note_data_write_possible",
        status="cataloged",
        completion_criteria=["notes/list/search classified", "note creation/edit/delete requires approval"],
        notes=["Private notes surface."],
    ),
    GoogleSurface(
        key="tasks",
        label="Google Tasks",
        url="https://tasks.google.com/embed/",
        category="workspace",
        access_mode="api_preferred",
        risk="task_data_write_possible",
        status="cataloged",
        completion_criteria=["task list/read separated from create/update/delete", "mutations require approval"],
        notes=["Prefer Tasks API where available."],
    ),
    GoogleSurface(
        key="photos",
        label="Google Photos",
        url="https://photos.google.com/",
        category="media_private",
        access_mode="manual_live_read",
        risk="private_media_write_possible",
        status="cataloged",
        completion_criteria=["library/albums classified", "upload/delete/share requires approval"],
        notes=["Private media surface."],
    ),
    GoogleSurface(
        key="maps_platform",
        label="Google Maps Platform",
        url="https://console.cloud.google.com/google/maps-apis",
        category="developer_console",
        access_mode="manual_live_read_or_api",
        risk="api_key_billing_write_possible",
        status="cataloged",
        completion_criteria=["project/API context recorded", "key, billing, quota changes require approval"],
        notes=["Maps Platform is managed through Cloud Console."],
    ),
    GoogleSurface(
        key="business_profile",
        label="Google Business Profile",
        url="https://business.google.com/",
        category="business",
        access_mode="manual_live_read_or_api",
        risk="public_business_listing_write_possible",
        status="cataloged",
        completion_criteria=["profile/location context recorded", "post, listing, hours, reply changes require approval"],
        notes=["Public business listing changes require explicit approval."],
    ),
    GoogleSurface(
        key="analytics",
        label="Google Analytics",
        url="https://analytics.google.com/",
        category="marketing_analytics",
        access_mode="manual_live_read_or_api",
        risk="analytics_config_write_possible",
        status="cataloged",
        completion_criteria=["property/account context recorded", "config/export/share changes require approval"],
        notes=["Prefer Analytics API for reporting."],
    ),
    GoogleSurface(
        key="tag_manager",
        label="Google Tag Manager",
        url="https://tagmanager.google.com/",
        category="marketing_analytics",
        access_mode="manual_live_read_or_api",
        risk="site_tag_publish_possible",
        status="cataloged",
        completion_criteria=["container/workspace context recorded", "publish/version changes require approval"],
        notes=["Publishing tags can affect production sites."],
    ),
    GoogleSurface(
        key="ads",
        label="Google Ads",
        url="https://ads.google.com/",
        category="marketing",
        access_mode="manual_live_read_or_api",
        risk="ad_spend_write_possible",
        status="cataloged",
        completion_criteria=["account/campaign context recorded", "budget/campaign/ad changes require approval"],
        notes=["Spend-affecting actions require strict approval."],
    ),
    GoogleSurface(
        key="merchant_center",
        label="Google Merchant Center",
        url="https://merchants.google.com/",
        category="commerce",
        access_mode="manual_live_read_or_api",
        risk="product_listing_write_possible",
        status="cataloged",
        completion_criteria=["account/product context recorded", "feed/product/policy actions require approval"],
        notes=["Commerce listing surface."],
    ),
    GoogleSurface(
        key="adsense",
        label="Google AdSense",
        url="https://adsense.google.com/adsense/login",
        category="monetization",
        access_mode="manual_live_read",
        risk="monetization_config_write_possible",
        status="cataloged",
        completion_criteria=["account/site context recorded", "payment/ad unit changes require approval"],
        notes=["Monetization and payment-sensitive surface."],
    ),
    GoogleSurface(
        key="looker_studio",
        label="Looker Studio",
        url="https://lookerstudio.google.com/",
        category="analytics",
        access_mode="manual_live_read_or_api",
        risk="report_data_share_write_possible",
        status="cataloged",
        completion_criteria=["reports/data sources classified", "share/edit/create requires approval"],
        notes=["Reporting and data-source surface."],
    ),
    GoogleSurface(
        key="google_developers",
        label="Google for Developers",
        url="https://developers.google.com/products",
        category="developer_docs",
        access_mode="browser_readonly",
        risk="public_read",
        status="cataloged",
        completion_criteria=["developer product categories mapped", "no login state change attempted"],
        notes=["Official developer product index."],
    ),
    GoogleSurface(
        key="chrome_developers",
        label="Chrome for Developers",
        url="https://developer.chrome.com/",
        category="developer_docs",
        access_mode="browser_readonly",
        risk="public_read",
        status="cataloged",
        completion_criteria=["Chrome docs/tools mapped", "no login state change attempted"],
        notes=["Official Chrome developer surface."],
    ),
    GoogleSurface(
        key="apps_script",
        label="Google Apps Script",
        url="https://script.google.com/home",
        category="developer_console",
        access_mode="manual_live_read_or_api",
        risk="script_deploy_write_possible",
        status="cataloged",
        completion_criteria=["project context recorded", "script edit/deploy/auth changes require approval"],
        notes=["Apps Script can access Workspace data."],
    ),
    GoogleSurface(
        key="colab",
        label="Google Colab",
        url="https://colab.research.google.com/",
        category="developer_console",
        access_mode="manual_live_read",
        risk="notebook_code_execution_possible",
        status="cataloged",
        completion_criteria=["notebook/runtime state classified", "code execution requires approval"],
        notes=["Notebook execution can run arbitrary code."],
    ),
    GoogleSurface(
        key="cloud_apis_credentials",
        label="Google Cloud APIs and Credentials",
        url="https://console.cloud.google.com/apis/credentials",
        category="developer_console",
        access_mode="manual_live_read_or_api",
        risk="credential_key_write_possible",
        status="cataloged",
        completion_criteria=["project context recorded", "credential creation/deletion requires approval"],
        notes=["API keys/OAuth/service accounts are sensitive."],
    ),
    GoogleSurface(
        key="cloud_iam",
        label="Google Cloud IAM",
        url="https://console.cloud.google.com/iam-admin/iam",
        category="developer_console",
        access_mode="manual_live_read_or_api",
        risk="iam_write_possible",
        status="cataloged",
        completion_criteria=["project context recorded", "grant/revoke role changes require approval"],
        notes=["IAM changes are high risk."],
    ),
    GoogleSurface(
        key="cloud_billing",
        label="Google Cloud Billing",
        url="https://console.cloud.google.com/billing",
        category="developer_console",
        access_mode="manual_live_read",
        risk="billing_write_possible",
        status="cataloged",
        completion_criteria=["billing account context recorded", "payment/budget/link changes require approval"],
        notes=["Billing changes require explicit approval."],
    ),
    GoogleSurface(
        key="cloud_run",
        label="Cloud Run",
        url="https://console.cloud.google.com/run",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="deploy_write_possible",
        status="cataloged",
        completion_criteria=["service/project context recorded", "deploy/config changes require approval"],
        notes=["Prefer gcloud/API for controlled deploys."],
    ),
    GoogleSurface(
        key="compute_engine",
        label="Compute Engine",
        url="https://console.cloud.google.com/compute",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="compute_resource_write_possible",
        status="cataloged",
        completion_criteria=["project/zone context recorded", "VM/network/disk changes require approval"],
        notes=["Infrastructure changes are approval-gated."],
    ),
    GoogleSurface(
        key="cloud_storage",
        label="Cloud Storage",
        url="https://console.cloud.google.com/storage",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="storage_write_possible",
        status="cataloged",
        completion_criteria=["project/bucket context recorded", "bucket/object/IAM changes require approval"],
        notes=["Storage changes can expose/delete data."],
    ),
    GoogleSurface(
        key="bigquery",
        label="BigQuery",
        url="https://console.cloud.google.com/bigquery",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="data_query_or_write_possible",
        status="cataloged",
        completion_criteria=["project/dataset context recorded", "query export/delete changes require approval"],
        notes=["Queries can incur costs or expose data."],
    ),
    GoogleSurface(
        key="gke",
        label="Google Kubernetes Engine",
        url="https://console.cloud.google.com/kubernetes",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="cluster_write_possible",
        status="cataloged",
        completion_criteria=["project/cluster context recorded", "cluster/deploy changes require approval"],
        notes=["Cluster changes are high risk."],
    ),
    GoogleSurface(
        key="cloud_sql",
        label="Cloud SQL",
        url="https://console.cloud.google.com/sql",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="database_write_possible",
        status="cataloged",
        completion_criteria=["project/instance context recorded", "instance/database changes require approval"],
        notes=["Database changes require approval."],
    ),
    GoogleSurface(
        key="pubsub",
        label="Pub/Sub",
        url="https://console.cloud.google.com/cloudpubsub",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="messaging_write_possible",
        status="cataloged",
        completion_criteria=["topic/subscription context recorded", "create/delete/publish requires approval"],
        notes=["Messaging changes can affect production systems."],
    ),
    GoogleSurface(
        key="secret_manager",
        label="Secret Manager",
        url="https://console.cloud.google.com/security/secret-manager",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="secret_write_possible",
        status="cataloged",
        completion_criteria=["project context recorded", "secret view/create/update requires approval"],
        notes=["Do not expose secret values in logs."],
    ),
    GoogleSurface(
        key="cloud_logging",
        label="Cloud Logging",
        url="https://console.cloud.google.com/logs",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="logs_private_data",
        status="cataloged",
        completion_criteria=["project/query context recorded", "sink/export/config changes require approval"],
        notes=["Logs may contain private data."],
    ),
    GoogleSurface(
        key="cloud_monitoring",
        label="Cloud Monitoring",
        url="https://console.cloud.google.com/monitoring",
        category="cloud_product",
        access_mode="manual_live_read_or_api",
        risk="monitoring_config_write_possible",
        status="cataloged",
        completion_criteria=["project context recorded", "alert/dashboard changes require approval"],
        notes=["Monitoring configuration surface."],
    ),
    GoogleSurface(
        key="vertex_ai",
        label="Vertex AI",
        url="https://console.cloud.google.com/vertex-ai",
        category="ai_console",
        access_mode="manual_live_read_or_api",
        risk="model_training_deploy_write_possible",
        status="cataloged",
        completion_criteria=["project/model context recorded", "training/deploy/job changes require approval"],
        notes=["Cloud AI execution can incur cost."],
    ),
)


def build_surface_catalog(surfaces: Iterable[GoogleSurface] = GOOGLE_SURFACES) -> dict:
    items = [asdict(surface) for surface in surfaces]
    return {
        "site_id": "google",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "policy": {
            "default": "static_catalog_first",
            "live_browser": "read_only_until_approved",
            "writes": "dry_run_and_explicit_approval_required",
            "login": "user_present_or_oauth_only",
        },
        "counts": {
            "surfaces": len(items),
            "api_preferred": sum(1 for item in items if item["access_mode"] == "api_preferred"),
            "manual_live": sum(1 for item in items if "manual_live" in item["access_mode"]),
        },
        "surfaces": items,
    }


def save_surface_catalog(catalog: dict | None = None, path: Path | None = None) -> Path:
    catalog = catalog or build_surface_catalog()
    return save_json_with_latest(catalog, REPORT_DIR, LATEST_CATALOG, "google_surface_catalog", path)


def print_surface_summary(catalog: dict, path: Path) -> None:
    print("=" * 60)
    print("Google surface catalog")
    print("=" * 60)
    print(f"saved: {path}")
    print(f"latest: {LATEST_CATALOG}")
    print(f"surfaces: {catalog['counts']['surfaces']}")
    print(f"api_preferred: {catalog['counts']['api_preferred']}")
    print(f"manual_live: {catalog['counts']['manual_live']}")
    for item in catalog["surfaces"]:
        print(f"- {item['key']}: {item['label']} [{item['risk']}] {item['status']}")
