"""Google work action definitions (read + write) and lookup helpers."""

from __future__ import annotations

from scripts.google.common import surfaces
from scripts.google.common.workflows_common import GoogleWorkAction


def _read_actions() -> tuple[GoogleWorkAction, ...]:
    actions: list[GoogleWorkAction] = []
    for item in surfaces.build_surface_catalog()["surfaces"]:
        actions.append(
            GoogleWorkAction(
                key=f"{item['key']}_open",
                surface_key=item["key"],
                label=f"Open/read {item['label']}",
                operation="read",
                target_url=item["url"],
                risk=item["risk"],
                requires_approval=False,
                required_inputs=[],
                prepare_outputs=["surface_context", "visible_controls", "completion_notes"],
                execute_mode="browser_open_readonly",
                status="implemented",
            )
        )
    return tuple(actions)


WRITE_ACTIONS: tuple[GoogleWorkAction, ...] = (
    GoogleWorkAction(
        key="gmail_send_email",
        surface_key="gmail",
        label="Prepare and send Gmail message",
        operation="send",
        target_url="https://mail.google.com/mail/u/0/#inbox?compose=new",
        risk="private_data_send",
        requires_approval=True,
        required_inputs=["to", "subject", "body"],
        prepare_outputs=["draft_plan", "recipient_validation", "send_confirmation"],
        execute_mode="api_preferred_or_browser_final_click",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="drive_upload_share_file",
        surface_key="drive",
        label="Upload and share Drive file",
        operation="upload_share",
        target_url="https://drive.google.com/drive/u/0/my-drive",
        risk="private_data_write_share",
        requires_approval=True,
        required_inputs=["local_path", "folder", "share_target", "role"],
        prepare_outputs=["upload_plan", "share_plan", "permission_diff"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="calendar_create_event",
        surface_key="calendar",
        label="Create Calendar event",
        operation="create",
        target_url="https://calendar.google.com/calendar/u/0/r/eventedit",
        risk="private_calendar_write",
        requires_approval=True,
        required_inputs=["title", "start", "end", "attendees"],
        prepare_outputs=["event_payload", "attendee_check", "timezone_check"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="docs_create_edit_document",
        surface_key="docs",
        label="Create or edit Docs document",
        operation="create_edit",
        target_url="https://docs.google.com/document/u/0/",
        risk="private_doc_write",
        requires_approval=True,
        required_inputs=["title", "content_source", "share_target"],
        prepare_outputs=["document_outline", "content_diff", "share_plan"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="sheets_update_cells",
        surface_key="sheets",
        label="Update Sheets cells",
        operation="update",
        target_url="https://docs.google.com/spreadsheets/u/0/",
        risk="private_sheet_write",
        requires_approval=True,
        required_inputs=["spreadsheet", "range", "values"],
        prepare_outputs=["cell_diff", "backup_plan", "validation_summary"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="slides_create_presentation",
        surface_key="slides",
        label="Create Slides presentation",
        operation="create",
        target_url="https://docs.google.com/presentation/u/0/",
        risk="private_presentation_write",
        requires_approval=True,
        required_inputs=["title", "deck_source", "share_target"],
        prepare_outputs=["deck_outline", "asset_manifest", "share_plan"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="forms_create_publish",
        surface_key="forms",
        label="Create and publish Forms form",
        operation="create_publish",
        target_url="https://docs.google.com/forms/u/0/",
        risk="form_publish_write",
        requires_approval=True,
        required_inputs=["title", "questions", "response_destination"],
        prepare_outputs=["form_schema", "response_plan", "publish_checklist"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="meet_create_meeting",
        surface_key="meet",
        label="Create Meet meeting",
        operation="create",
        target_url="https://meet.google.com/",
        risk="meeting_create_or_join",
        requires_approval=True,
        required_inputs=["title", "attendees", "time"],
        prepare_outputs=["meeting_plan", "attendee_check"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="chat_send_message",
        surface_key="chat",
        label="Send Google Chat message",
        operation="send",
        target_url="https://chat.google.com/",
        risk="message_send",
        requires_approval=True,
        required_inputs=["space_or_user", "message"],
        prepare_outputs=["message_preview", "target_check"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="contacts_create_update",
        surface_key="contacts",
        label="Create or update Contact",
        operation="create_update",
        target_url="https://contacts.google.com/",
        risk="contact_data_write",
        requires_approval=True,
        required_inputs=["name", "email", "phone"],
        prepare_outputs=["contact_diff", "duplicate_check"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="keep_create_note",
        surface_key="keep",
        label="Create Keep note",
        operation="create",
        target_url="https://keep.google.com/",
        risk="note_data_write",
        requires_approval=True,
        required_inputs=["title", "body"],
        prepare_outputs=["note_preview"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="tasks_create_task",
        surface_key="tasks",
        label="Create Google Task",
        operation="create",
        target_url="https://tasks.google.com/embed/",
        risk="task_data_write",
        requires_approval=True,
        required_inputs=["title", "due"],
        prepare_outputs=["task_payload", "list_check"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="photos_upload_share",
        surface_key="photos",
        label="Upload and share Google Photos media",
        operation="upload_share",
        target_url="https://photos.google.com/",
        risk="private_media_write_share",
        requires_approval=True,
        required_inputs=["local_path", "album", "share_target"],
        prepare_outputs=["media_manifest", "album_check", "share_plan"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="youtube_comment_or_subscribe",
        surface_key="youtube",
        label="Comment, like, or subscribe on YouTube",
        operation="public_interaction",
        target_url="https://www.youtube.com/",
        risk="public_account_interaction",
        requires_approval=True,
        required_inputs=["target_url", "action", "text"],
        prepare_outputs=["interaction_preview", "account_check"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="youtube_studio_upload_video",
        surface_key="youtube_studio",
        label="Upload YouTube Studio video",
        operation="upload_publish",
        target_url="https://studio.youtube.com/",
        risk="channel_publish_write",
        requires_approval=True,
        required_inputs=["video_path", "title", "description", "visibility"],
        prepare_outputs=["upload_manifest", "metadata_preview", "publish_checklist"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="youtube_studio_edit_video_metadata",
        surface_key="youtube_studio",
        label="Edit YouTube Studio video metadata",
        operation="edit",
        target_url="https://studio.youtube.com/",
        risk="channel_metadata_write",
        requires_approval=True,
        required_inputs=["video_id_or_url", "title", "description", "visibility"],
        prepare_outputs=["metadata_diff", "publish_checklist"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="search_console_submit_indexing",
        surface_key="search_console",
        label="Submit Search Console indexing request",
        operation="submit",
        target_url="https://search.google.com/search-console",
        risk="site_indexing_write",
        requires_approval=True,
        required_inputs=["property", "url"],
        prepare_outputs=["property_check", "url_inspection_plan"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="search_console_submit_sitemap",
        surface_key="search_console",
        label="Submit Search Console sitemap",
        operation="submit",
        target_url="https://search.google.com/search-console/sitemaps",
        risk="site_indexing_write",
        requires_approval=True,
        required_inputs=["property", "sitemap_url"],
        prepare_outputs=["property_check", "sitemap_validation"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="ai_studio_create_api_key",
        surface_key="ai_studio",
        label="Create Google AI Studio API key",
        operation="create_key",
        target_url="https://aistudio.google.com/app/apikey",
        risk="credential_key_write",
        requires_approval=True,
        required_inputs=["project", "key_label"],
        prepare_outputs=["project_check", "key_policy", "secret_storage_plan"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="gemini_submit_prompt",
        surface_key="gemini",
        label="Submit Gemini prompt",
        operation="submit_prompt",
        target_url="https://gemini.google.com/",
        risk="private_prompt_submission",
        requires_approval=True,
        required_inputs=["prompt"],
        prepare_outputs=["prompt_preview", "data_sensitivity_check"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="play_console_prepare_release",
        surface_key="play_console",
        label="Prepare Google Play app release",
        operation="release",
        target_url="https://play.google.com/console/",
        risk="app_release_publish",
        requires_approval=True,
        required_inputs=["app", "track", "artifact_path", "release_notes"],
        prepare_outputs=["release_manifest", "track_check", "policy_checklist"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="firebase_deploy_rules",
        surface_key="firebase_console",
        label="Deploy Firebase rules/config",
        operation="deploy",
        target_url="https://console.firebase.google.com/",
        risk="infra_rules_write",
        requires_approval=True,
        required_inputs=["project", "rules_path", "target"],
        prepare_outputs=["rules_diff", "project_check", "rollback_plan"],
        execute_mode="cli_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="cloud_create_api_credential",
        surface_key="cloud_apis_credentials",
        label="Create Google Cloud API credential",
        operation="create_key",
        target_url="https://console.cloud.google.com/apis/credentials",
        risk="credential_key_write",
        requires_approval=True,
        required_inputs=["project", "credential_type", "label"],
        prepare_outputs=["project_check", "credential_policy", "secret_storage_plan"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="cloud_iam_change_role",
        surface_key="cloud_iam",
        label="Change Google Cloud IAM role",
        operation="iam_change",
        target_url="https://console.cloud.google.com/iam-admin/iam",
        risk="iam_write",
        requires_approval=True,
        required_inputs=["project", "principal", "role", "change"],
        prepare_outputs=["iam_diff", "least_privilege_check", "rollback_plan"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="cloud_billing_budget_or_link",
        surface_key="cloud_billing",
        label="Change Google Cloud billing budget/link",
        operation="billing_change",
        target_url="https://console.cloud.google.com/billing",
        risk="billing_write",
        requires_approval=True,
        required_inputs=["billing_account", "project", "change"],
        prepare_outputs=["billing_diff", "cost_impact_check"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="cloud_run_deploy_service",
        surface_key="cloud_run",
        label="Deploy Cloud Run service",
        operation="deploy",
        target_url="https://console.cloud.google.com/run",
        risk="deploy_write",
        requires_approval=True,
        required_inputs=["project", "service", "region", "image"],
        prepare_outputs=["deploy_manifest", "env_diff", "rollback_plan"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="compute_engine_create_vm",
        surface_key="compute_engine",
        label="Create Compute Engine VM",
        operation="create",
        target_url="https://console.cloud.google.com/compute/instances",
        risk="compute_resource_write",
        requires_approval=True,
        required_inputs=["project", "zone", "machine_type", "image"],
        prepare_outputs=["vm_manifest", "cost_check", "network_check"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="cloud_storage_create_bucket",
        surface_key="cloud_storage",
        label="Create Cloud Storage bucket",
        operation="create",
        target_url="https://console.cloud.google.com/storage/browser",
        risk="storage_write",
        requires_approval=True,
        required_inputs=["project", "bucket", "location", "access"],
        prepare_outputs=["bucket_manifest", "iam_check", "lifecycle_check"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="bigquery_run_query_or_export",
        surface_key="bigquery",
        label="Run BigQuery query or export",
        operation="query_export",
        target_url="https://console.cloud.google.com/bigquery",
        risk="data_query_or_export",
        requires_approval=True,
        required_inputs=["project", "query_or_job", "destination"],
        prepare_outputs=["query_preview", "cost_check", "data_sensitivity_check"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="gke_apply_change",
        surface_key="gke",
        label="Apply Google Kubernetes Engine change",
        operation="apply",
        target_url="https://console.cloud.google.com/kubernetes",
        risk="cluster_write",
        requires_approval=True,
        required_inputs=["project", "cluster", "manifest_path"],
        prepare_outputs=["manifest_diff", "cluster_check", "rollback_plan"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="cloud_sql_change_instance",
        surface_key="cloud_sql",
        label="Change Cloud SQL instance",
        operation="change",
        target_url="https://console.cloud.google.com/sql",
        risk="database_write",
        requires_approval=True,
        required_inputs=["project", "instance", "change"],
        prepare_outputs=["database_diff", "backup_check", "rollback_plan"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="pubsub_create_or_publish",
        surface_key="pubsub",
        label="Create Pub/Sub resource or publish message",
        operation="create_publish",
        target_url="https://console.cloud.google.com/cloudpubsub",
        risk="messaging_write",
        requires_approval=True,
        required_inputs=["project", "topic_or_subscription", "payload"],
        prepare_outputs=["resource_diff", "message_preview"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="secret_manager_create_update",
        surface_key="secret_manager",
        label="Create or update Secret Manager secret",
        operation="create_update",
        target_url="https://console.cloud.google.com/security/secret-manager",
        risk="secret_write",
        requires_approval=True,
        required_inputs=["project", "secret_name", "secret_source"],
        prepare_outputs=["secret_metadata", "redaction_check", "iam_check"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="cloud_logging_create_sink",
        surface_key="cloud_logging",
        label="Create Cloud Logging sink/query config",
        operation="create",
        target_url="https://console.cloud.google.com/logs",
        risk="logs_config_write",
        requires_approval=True,
        required_inputs=["project", "sink_or_query", "destination"],
        prepare_outputs=["log_filter_preview", "destination_check"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="cloud_monitoring_create_alert",
        surface_key="cloud_monitoring",
        label="Create Cloud Monitoring alert/dashboard",
        operation="create",
        target_url="https://console.cloud.google.com/monitoring",
        risk="monitoring_config_write",
        requires_approval=True,
        required_inputs=["project", "policy_or_dashboard", "notification_channel"],
        prepare_outputs=["policy_preview", "channel_check"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="vertex_ai_start_job_or_deploy",
        surface_key="vertex_ai",
        label="Start Vertex AI job or deployment",
        operation="job_deploy",
        target_url="https://console.cloud.google.com/vertex-ai",
        risk="ai_cost_deploy_write",
        requires_approval=True,
        required_inputs=["project", "job_or_model", "config"],
        prepare_outputs=["job_manifest", "cost_check", "data_sensitivity_check"],
        execute_mode="cli_or_api_preferred",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="apps_script_deploy",
        surface_key="apps_script",
        label="Deploy Apps Script project",
        operation="deploy",
        target_url="https://script.google.com/home",
        risk="script_deploy_write",
        requires_approval=True,
        required_inputs=["project", "version", "deployment_target"],
        prepare_outputs=["script_diff", "oauth_scope_check", "rollback_plan"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="colab_execute_notebook",
        surface_key="colab",
        label="Execute Colab notebook",
        operation="execute",
        target_url="https://colab.research.google.com/",
        risk="notebook_code_execution",
        requires_approval=True,
        required_inputs=["notebook", "runtime", "parameters"],
        prepare_outputs=["notebook_diff", "runtime_check", "data_sensitivity_check"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="maps_platform_change_key_or_quota",
        surface_key="maps_platform",
        label="Change Maps Platform key/quota",
        operation="change",
        target_url="https://console.cloud.google.com/google/maps-apis",
        risk="api_key_billing_write",
        requires_approval=True,
        required_inputs=["project", "api_or_key", "change"],
        prepare_outputs=["key_or_quota_diff", "billing_check"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="business_profile_post_or_update",
        surface_key="business_profile",
        label="Post or update Google Business Profile",
        operation="post_update",
        target_url="https://business.google.com/",
        risk="public_business_listing_write",
        requires_approval=True,
        required_inputs=["location", "change", "content"],
        prepare_outputs=["listing_diff", "public_preview"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="analytics_export_or_configure",
        surface_key="analytics",
        label="Export or configure Google Analytics",
        operation="export_configure",
        target_url="https://analytics.google.com/",
        risk="analytics_data_or_config",
        requires_approval=True,
        required_inputs=["property", "report_or_change", "destination"],
        prepare_outputs=["report_plan", "config_diff", "share_check"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="tag_manager_publish_version",
        surface_key="tag_manager",
        label="Publish Google Tag Manager version",
        operation="publish",
        target_url="https://tagmanager.google.com/",
        risk="site_tag_publish",
        requires_approval=True,
        required_inputs=["account", "container", "workspace", "version_notes"],
        prepare_outputs=["tag_diff", "preview_check", "rollback_plan"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="ads_campaign_budget_change",
        surface_key="ads",
        label="Change Google Ads campaign/budget",
        operation="campaign_change",
        target_url="https://ads.google.com/",
        risk="ad_spend_write",
        requires_approval=True,
        required_inputs=["account", "campaign", "change"],
        prepare_outputs=["spend_impact", "campaign_diff", "approval_summary"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="merchant_center_product_update",
        surface_key="merchant_center",
        label="Update Merchant Center product/feed",
        operation="product_update",
        target_url="https://merchants.google.com/",
        risk="product_listing_write",
        requires_approval=True,
        required_inputs=["account", "product_or_feed", "change"],
        prepare_outputs=["product_diff", "policy_check", "feed_validation"],
        execute_mode="api_preferred_or_browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="adsense_ad_unit_or_payment_change",
        surface_key="adsense",
        label="Change AdSense ad unit/payment setting",
        operation="change",
        target_url="https://adsense.google.com/adsense/login",
        risk="monetization_config_write",
        requires_approval=True,
        required_inputs=["account", "site", "change"],
        prepare_outputs=["monetization_diff", "payment_safety_check"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
    GoogleWorkAction(
        key="looker_studio_create_or_share_report",
        surface_key="looker_studio",
        label="Create or share Looker Studio report",
        operation="create_share",
        target_url="https://lookerstudio.google.com/",
        risk="report_data_share_write",
        requires_approval=True,
        required_inputs=["report", "data_source", "share_target"],
        prepare_outputs=["report_plan", "data_source_check", "share_plan"],
        execute_mode="browser_handoff",
        status="implemented_gated",
    ),
)


GOOGLE_WORK_ACTIONS: tuple[GoogleWorkAction, ...] = _read_actions() + WRITE_ACTIONS


def get_action(action_key: str) -> GoogleWorkAction:
    for action in GOOGLE_WORK_ACTIONS:
        if action.key == action_key:
            return action
    raise KeyError(f"unknown google work action: {action_key}")


def parse_kv_args(args: list[str]) -> dict[str, str]:
    values: dict[str, str] = {}
    for arg in args:
        if "=" not in arg:
            continue
        key, value = arg.split("=", 1)
        if key:
            values[key] = value
    return values
